services:

  chess_server:
    image: python:3.10
    container_name: chess_server
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "8888:8888"
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:4.4
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: zhaoyun
      MONGO_INITDB_ROOT_PASSWORD: 801129